<<<<<<< HEAD
site_name: Nicole's Fab site

theme:
        name: readthedocs
        
nav:
        - 主页: index.md
        - 关于: aboutme.md
=======
site_name: Nicole's Fab site

theme:
        name: readthedocs
        
nav:
        - 主页: index.md
        - 关于: aboutme.md
>>>>>>> aeb0b328e317276a8577ce08a456f4ea334d1949
